Repository YACLib/YACLib, pull requests merged in 2021-07, with the labels that each got.

#1 Initial commit and task implementation
  .clang-format
  .gitattributes
  .gitignore
  CMakeLists.txt
  include/yaclib/container/intrusive_node.hpp
  include/yaclib/executor/executor.hpp
  include/yaclib/executor/thread_factory.hpp
  include/yaclib/executor/thread_pool.hpp
  include/yaclib/task.hpp
  src/CMakeLists.txt
  src/config.hpp.in
  src/container/CMakeLists.txt
  src/container/intrusive_list.cpp
  src/container/intrusive_list.hpp
  src/executor/CMakeLists.txt
  src/executor/thread_factory.cpp
  src/executor/thread_pool.cpp
  test/CMakeLists.txt
  test/task.cpp
  test/thread_factory.cpp
Labels: enhancement, good first issue

#23 Added single-threaded tests for thread factory
  include/yaclib/container/intrusive_node.hpp
  include/yaclib/executor/thread_factory.hpp
  include/yaclib/task.hpp
  src/CMakeLists.txt
  src/executor/thread_pool.cpp
  test/CMakeLists.txt
  test/thread_factory.cpp
Labels: enhancement

#30 #6 Added first CI try
  .clang-format
  .github/workflows/clang-format.yml
  .github/workflows/ubuntu_pull_request.yml
  .github/workflows/ubuntu_push.yml
Labels: enhancement

#32 First simple CPU bounded static thread pool
  include/yaclib/container/intrusive_node.hpp
  include/yaclib/executor/executor.hpp
  include/yaclib/executor/thread_factory.hpp
  include/yaclib/executor/thread_pool.hpp
  include/yaclib/task.hpp
  src/container/intrusive_list.cpp
  src/container/intrusive_list.hpp
  src/executor/thread_factory.cpp
  src/executor/thread_pool.cpp
  test/CMakeLists.txt
  test/task.cpp
  test/thread_factory.cpp
  test/thread_pool.cpp
  test/util/cpu_time.hpp
  test/util/time.hpp
Labels: enhancement

#36 Add clang tidy
  .clang-format
  .clang-tidy
Labels: documentation

#37 Add AsyncMutex
  .clang-format
  CMakeLists.txt
  include/yaclib/executor/async_mutex.hpp
  include/yaclib/executor/executor.hpp
  include/yaclib/executor/thread_factory.hpp
  include/yaclib/executor/thread_pool.hpp
  include/yaclib/ref.hpp
  include/yaclib/task.hpp
  src/CMakeLists.txt
  src/container/CMakeLists.txt
  src/container/mpsc_stack.hpp
  src/executor/CMakeLists.txt
  src/executor/async_mutex.cpp
  src/executor/thread_factory.cpp
  src/executor/thread_pool.cpp
  test/CMakeLists.txt
  test/async_mutex.cpp
  test/task.cpp
  test/thread_factory.cpp
  test/thread_pool.cpp
Labels: enhancement

#35 Add documentation
  README.md
  doc/DEPENDENCIES.md
  doc/INSTALL.md
  doc/STYLEGUIDE.md
  doc/TARGETS.md
Labels: documentation

#38 Add MSVC support and update CI
  .github/workflows/pull_request.yml
  .github/workflows/push.yml
  .github/workflows/ubuntu_pull_request.yml
  .github/workflows/ubuntu_push.yml
  src/CMakeLists.txt
  test/CMakeLists.txt
  test/thread_pool.cpp
  test/util/cpu_time.hpp
Labels: enhancement
