Repository YACLib/YACLib, pull requests merged in 2022-08, with the labels that each got.

#195 Remove Stop and small fixes
  .clang-format
  README.md
  doc/yaclib_std.md
  include/yaclib/algo/detail/when_any_impl.hpp
  include/yaclib/algo/one_shot_event.hpp
  include/yaclib/async/detail/base_core.hpp
  include/yaclib/async/detail/core.hpp
  include/yaclib/async/detail/future_impl.hpp
  include/yaclib/async/detail/inline_core.hpp
  include/yaclib/async/detail/result_core.hpp
  include/yaclib/async/future.hpp
  include/yaclib/util/detail/atomic_counter.hpp
  include/yaclib/util/result.hpp
  src/async/base_core.cpp
  src/executor/thread_factory.cpp
  src/fault/injector.cpp
  test/unit/algo/when_any.cpp
  test/unit/async/core_size.cpp
  test/unit/async/future.cpp
  test/unit/async/future_inline.cpp
  test/util/inline_helper.hpp
Labels: performance, refactoring

#197 Remove Future<std::array<...>> WhenAll specialization
  include/yaclib/algo/detail/when_all_impl.hpp
  include/yaclib/algo/when_all.hpp
  test/unit/algo/when_all.cpp
Labels: performance

#199 Add lazy pipeline
  README.md
  include/yaclib/async/detail/base_core.hpp
  include/yaclib/async/detail/core.hpp
  include/yaclib/async/detail/future_impl.hpp
  include/yaclib/async/future.hpp
  include/yaclib/async/run.hpp
  include/yaclib/async/task.hpp
  include/yaclib/coroutine/async_mutex.hpp
  include/yaclib/coroutine/detail/promise_type.hpp
  include/yaclib/coroutine/future_traits.hpp
  include/yaclib/executor/executor.hpp
  include/yaclib/executor/inline.hpp
  include/yaclib/executor/manual.hpp
  include/yaclib/fwd.hpp
  include/yaclib/util/result.hpp
  include/yaclib/util/type_traits.hpp
  src/async/CMakeLists.txt
  src/async/base_core.cpp
  src/async/task_impl.cpp
  src/executor/inline.cpp
  src/executor/manual.cpp
  src/executor/strand.cpp
  src/executor/thread_pool.cpp
  test/CMakeLists.txt
  test/unit/async/future.cpp
  test/unit/async/future_inline.cpp
  test/unit/async/make_future.cpp
  test/unit/async/make_task.cpp
  test/unit/async/task.cpp
  test/unit/coroutine/async_mutex.cpp
  test/unit/coroutine/await.cpp
  test/util/async_suite.hpp
Labels: enhancement, test
